@SemanticKernalApplication_HostAddress = https://localhost:7026

POST {{SemanticKernalApplication_HostAddress}}/themegenerator
Accept: application/json
{
    "Brand": "HIBrand",
    "DeviceId": "37.785834",
    "UserPrompt": "",
    "ThemeId": "",
    "ScreenName":"",
    "SiteName":"mav-site-a"
}
###
